cloud:
  aws:
    credentials:
      access-key: xxxxxx    #Kindly put Your Own access-key. Find/Generate it from (Click to your right side UserName navigation bar-> My Security Credentials -> IAM page -> access-key).
      secret-key: xxxxxx    #Kindly put Your Own secret-Key. Find/Generate it from (UserName -> My Security Credentials -> IAM page -> secret-key).
    region:
      static: xxxxx  #Kindly put your own AWS region.


server:
   port: 8081
