cloud:
  aws:
    credentials:
      access-key: xxxxx    #Kindly put Your Own access-key. Find/Generate it from (Click to your right side UserName navigation bar-> My Security Credentials -> IAM page -> access-key).
      secret-key: xxxxx    #Kindly put Your Own secret-Key. Find/Generate it from (UserName -> My Security Credentials -> IAM page -> secret-key).
    region:
      static: ap-south-1   #Provide your own AWS region.
    stack:
      auto: false

application:
  bucket:
    name: xxxxxx   #Provide your own unique AWS s3 bucket name.


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 3MB
      max-file-size: 8MB
      max-request-size: 12MB

server:
  port: 8081
