cloud:
  aws:
    credentials:
      access-key: AKIAJ2TK3JEGA34EBBUA
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: my-s3-strorages


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 3MB
      max-file-size: 8MB
      max-request-size: 12MB

server:
  port: 8081